/var/log/nginx/*.log
/var/log/php/*.log
/var/log/supervisord/*.log
/var/log/laravel/scheduler/*.log
/var/log/laravel/queue/*.log
/var/log/logrotate/*.log
{
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    copytruncate
}