server {
    listen 80 default_server;
    index index.php index.html;
    server_name localhost;
    error_log  /var/log/nginx/nginx.error.log;
    access_log /var/log/nginx/nginx.access.log;
    root /var/www/public;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_hide_header X-Powered-By;

        # Tells PHP we're using a reverse proxy with TLS termination
        fastcgi_param HTTPS on;
        fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        fastcgi_param HTTP_X_FORWARDED_SSL on;
        add_header Content-Security-Policy "upgrade-insecure-requests" always;
    }

    location ~* \.(jpg|jpeg|png|gif|webp|svg|ico|css|js|woff|woff2|ttf|eot)$ {
        expires 1y;                          # Cache these assets for 1 year
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable"; # Set caching header
    }

    location ~* ^/build/assets/.*$ {
        expires 1y;                          # Cache these assets for 1 year
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable"; # Set caching header
    }

    location ~* \.(?:html)$ {
        expires -1;                          # Do not cache HTML files
        add_header Cache-Control "no-store, must-revalidate";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ ^/flux/flux(\.min)?\.(js|css)$ {
        expires off;
        try_files $uri $uri/ /index.php?$query_string;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable"; # Set caching header
    }
}
