[global]
error_log = /var/log/php/php-fpm.err.log

; https://github.com/docker-library/php/pull/725#issuecomment-443540114
log_limit = 81920

[www]
; php-fpm closes STDOUT on startup, so sending logs to /proc/self/fd/1 does not work.
; https://bugs.php.net/bug.php?id=73886
access.log = /var/log/php/php-fpm.out.log
user = sail
group = sail

pm = dynamic
pm.max_children = 10
pm.start_servers = 3
pm.min_spare_servers = 2
pm.max_spare_servers = 10

clear_env = no

; Ensure worker stdout and stderr are sent to the main error log.
catch_workers_output = yes
decorate_workers_output = no
