memory_limit=512M
upload_max_filesize=20M
post_max_size=20M
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=192
opcache.max_accelerated_files=10000
opcache.validate_timestamps=0
opcache.preload=/var/www/bootstrap/opcache.preload.php
opcache.preload_user=www-data