memory_limit=512M
upload_max_filesize=20M
post_max_size=20M
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Xdebug 3
xdebug.mode = profile
xdebug.start_with_request = trigger
xdebug.profiler_output_name = cachegrind.out.%u.%r

; Xdebug 2
xdebug.profiler_enable_trigger = 1
xdebug.profiler_output_name = cachegrind.out.%u.%r