#!/bin/sh
if [ -f /var/www/.env ]; then
  DOMAIN=$(grep -E '^APP_URL=' /var/www/.env | cut -d '=' -f 2 | sed 's|http[s]*://||')
  ENVIRONMENT=$(grep -E '^APP_ENV=' /var/www/.env | cut -d '=' -f 2)
  BUCKET=$(grep -E '^AWS_BUCKET=' /var/www/.env | cut -d '=' -f 2)
  MINIO_USER=$(grep -E '^AWS_ACCESS_KEY_ID=' /var/www/.env | cut -d '=' -f 2)
  MINIO_PASS=$(grep -E '^AWS_SECRET_ACCESS_KEY=' /var/www/.env | cut -d '=' -f 2)
  DB_CONNECTION=$(grep -E '^DB_CONNECTION=' /var/www/.env | cut -d '=' -f 2)
  DB_HOST=$(grep -E '^DB_HOST=' /var/www/.env | cut -d '=' -f 2)
  DB_PORT=$(grep -E '^DB_PORT=' /var/www/.env | cut -d '=' -f 2)
  DB_USERNAME=$(grep -E '^DB_USERNAME=' /var/www/.env | cut -d '=' -f 2)
  DB_PASSWORD=$(grep -E '^DB_PASSWORD=' /var/www/.env | cut -d '=' -f 2)
else
  DOMAIN=$(echo $APP_URL | sed 's|http[s]*://||')
  ENVIRONMENT=$APP_ENV
  BUCKET=$AWS_BUCKET
  MINIO_USER=$AWS_ACCESS_KEY_ID
  MINIO_PASS=$AWS_SECRET_ACCESS_KEY
fi

# Fail fast
set -e

# echo "$(getent hosts minio | awk '{ print $1 }') $DOMAIN" >> /etc/hosts

if [ "$ENVIRONMENT" != "production" ]; then
  echo ""
  echo "==============================================="
  echo " Non-production environment detected."
  echo "==============================================="
  echo ""

else
  echo ""
  echo "==============================================="
  echo " Waiting for MinIO to be ready..."
  echo "==============================================="
  echo ""

  until curl -sk https://minio:9000/minio/health/ready; do
    echo >&2 "  [!] MinIO is unavailable - sleeping"
    sleep 2
  done

  echo "  [X] MinIO is ready - continuing..."

  echo ""
  echo "==============================================="
  echo " Setting up MinIO bucket and policies"
  echo "==============================================="
  echo ""

  # Set up alias and create bucket
  mc alias set localminio https://minio:9000 $MINIO_USER $MINIO_PASS
  mc mb --ignore-existing localminio/$BUCKET

  # You can even set bucket policy if needed
  mc anonymous set download localminio/$BUCKET

fi

# Check if the vendor directory exists
if [ ! -d "/var/www/vendor" ]; then
  echo ""
  echo "==============================================="
  echo " Running Composer Install..."
  echo "==============================================="
  echo ""
  composer install --no-dev --prefer-dist --optimize-autoloader
fi

echo ""
echo "==============================================="
echo " Waiting for $DB_CONNECTION to be ready..."
echo "==============================================="
echo ""

until nc -z $DB_HOST $DB_PORT; do
  echo >&2 "  [!] $DB_CONNECTION is unavailable - sleeping"
  sleep 2
done

echo "  [X] $DATABASE is ready - continuing..."

# Run database migrations and seed
echo ""
echo "==============================================="
echo " Running Laravel migrations and seeders..."
echo "==============================================="
echo ""
cd /var/www/

if php artisan migrate:status >/dev/null 2>&1; then
  echo "Database is exists and ready. Running migrations..."
  php artisan migrate --force
else
  echo "Database is not ready. Running fresh migrations and seeders..."
  php artisan migrate:fresh --force
  php artisan db:seed --force
fi

echo ""
echo "==============================================="
echo " Starting Supervisor Services..."
echo "==============================================="
echo ""

# Finally, start Supervisor (or whatever CMD you use)
exec "$@"

echo ""
echo "==============================================="
echo " https://$DOMAIN is ready to go!"
echo "==============================================="
