[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file = /tmp/supervisor.sock
chmod = 0777
chown= nobody:nogroup

[supervisorctl]
serverurl = unix:///tmp/supervisor.sock

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
user=sail
autostart=true
autorestart=true
environment=LARAVEL_SAIL="1"
stdout_logfile=/var/log/php/supervisor.out.log
stderr_logfile=/var/log/php/supervisor.err.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx/supervisor.out.log
stderr_logfile=/var/log/nginx/supervisor.err.log

[program:logrotate]
command=/bin/sh /usr/local/bin/logrotate-cron.sh
autostart=true
autorestart=true
stdout_logfile=/var/log/logrotate/logrotate.out.log
stderr_logfile=/var/log/logrotate/logrotate.err.log
