#!/usr/bin/env bash

# Fail early
set -e

# Run only if NIGHTWATCH_TOKEN is set and not empty
if [ -n "$NIGHTWATCH_TOKEN" ]; then
  # Check if the command nightwatch:agent exists in Artisan
  if php artisan | grep -q 'nightwatch:agent'; then
    exec s6-setuidgid www-data php artisan nightwatch:agent
  else
    echo "Command nightwatch:agent not found. Skipping nightwatch agent."
  fi
else
  echo "NIGHTWATCH_TOKEN not set. Skipping nightwatch agent."
fi

# Keep the service alive doing nothing
exec sleep infinity