#!/usr/bin/env bash

if [ -f .env ]; then
    SAIL_XDEBUG_MODE=$(grep 'SAIL_XDEBUG_MODE=' .env | sed 's/SAIL_XDEBUG_MODE=//g' | grep . || echo "off")
    export SAIL_XDEBUG_MODE
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
