name: Tests

on:
  push:
    branches: [1.x]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '8.2'
            laravel: 12
          - php: '8.3'
            laravel: 12
          - php: '8.4'
            laravel: 12
          - php: '8.5'
            laravel: 12

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'sail'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          tools: composer:v2
          coverage: none

      - name: Create a new Laravel application
        run: composer create-project laravel/laravel app "${{ matrix.laravel }}.x" --remove-vcs --no-interaction --prefer-dist

      - name: Link Sail repository
        run: |
          composer config minimum-stability dev
          composer config repositories.sail path ../sail
          composer require reyemtech/sail:* --dev -W
        working-directory: app

      - name: Install Sail
        run: |
          php artisan sail:install --php=${{ matrix.php }} --no-interaction
          php artisan sail:publish --no-interaction
        working-directory: app

      - name: Run PHPUnit tests
        run: cd ../sail && vendor/bin/phpunit
        working-directory: app
